create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  admission_number text unique,
  role text not null default 'student' check (role in ('admin', 'lecturer', 'student')),
  created_at timestamptz not null default now()
);

create table if not exists public.student_marks (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lecturer_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null,
  marks numeric(5,2) not null check (marks >= 0 and marks <= 100),
  grade text not null,
  remarks text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, subject)
);

create index if not exists idx_profiles_role_name on public.profiles(role, name);
create index if not exists idx_profiles_admission_role on public.profiles(admission_number, role);
create index if not exists idx_student_marks_student on public.student_marks(student_id);
create index if not exists idx_student_marks_lecturer on public.student_marks(lecturer_id);

alter table public.profiles enable row level security;
alter table public.student_marks enable row level security;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.grade_from_marks(mark_value numeric)
returns table (grade text, remarks text)
language sql
immutable
as $$
  select
    case
      when mark_value >= 80 then 'A'
      when mark_value >= 70 then 'B'
      when mark_value >= 60 then 'C'
      when mark_value >= 50 then 'D'
      else 'E'
    end,
    case
      when mark_value >= 80 then 'Excellent'
      when mark_value >= 70 then 'Very good'
      when mark_value >= 60 then 'Good'
      when mark_value >= 50 then 'Fair'
      else 'Needs improvement'
    end
$$;

create or replace function public.set_mark_grade()
returns trigger
language plpgsql
as $$
declare
  computed record;
begin
  select * into computed from public.grade_from_marks(new.marks);
  new.grade = computed.grade;
  new.remarks = computed.remarks;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_mark_grade on public.student_marks;
create trigger trg_set_mark_grade
before insert or update of marks on public.student_marks
for each row execute function public.set_mark_grade();

create or replace function public.resolve_login_identifier(login_identifier text, selected_role text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email
  from public.profiles
  where role = selected_role
    and (lower(email) = lower(login_identifier) or admission_number = login_identifier)
  limit 1
$$;

drop policy if exists "Profiles can read own profile" on public.profiles;
create policy "Profiles can read own profile"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
using (auth.uid() is not null);

drop policy if exists "Admins and lecturers can read student profiles" on public.profiles;
create policy "Admins and lecturers can read student profiles"
on public.profiles for select
using (
  public.current_profile_role() in ('admin', 'lecturer')
  and role = 'student'
);

drop policy if exists "Users can create their own student profile" on public.profiles;
create policy "Users can create their own student profile"
on public.profiles for insert
with check (auth.uid() = id and role = 'student');

drop policy if exists "Users can update own basic profile" on public.profiles;
create policy "Users can update own basic profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id and role = (select role from public.profiles where id = auth.uid()));

drop policy if exists "Students read own marks" on public.student_marks;
create policy "Students read own marks"
on public.student_marks for select
using (auth.uid() = student_id);

drop policy if exists "Admins and lecturers read marks" on public.student_marks;
create policy "Admins and lecturers read marks"
on public.student_marks for select
using (public.current_profile_role() in ('admin', 'lecturer'));

drop policy if exists "Admins and lecturers enter marks" on public.student_marks;
create policy "Admins and lecturers enter marks"
on public.student_marks for insert
with check (
  public.current_profile_role() in ('admin', 'lecturer')
  and lecturer_id = auth.uid()
);

drop policy if exists "Admins and lecturers update marks" on public.student_marks;
create policy "Admins and lecturers update marks"
on public.student_marks for update
using (public.current_profile_role() in ('admin', 'lecturer'))
with check (
  public.current_profile_role() in ('admin', 'lecturer')
  and lecturer_id = auth.uid()
);

-- After creating users in Supabase Auth, insert matching profiles here.
-- Example:
-- insert into public.profiles (id, name, email, admission_number, role)
-- values ('AUTH_USER_UUID', 'David Student', 'david.student@school.local', '20/194', 'student');
